=== dennismedeiros/veracode-platform-api-framework/platform-api-parsers/src/test/resources/xsd/filelist.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  Schema definition for the File List XML.
  Veracode, Inc., 2011.
-->
<xs:schema elementFormDefault="qualified" version="1.1"
   targetNamespace="https://analysiscenter.veracode.com/schema/2.0/filelist"
   xmlns:tns="https://analysiscenter.veracode.com/schema/2.0/filelist"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="filelist">
        <xs:annotation>
            <xs:documentation>
                This is a wrapper for the entire File List xml file.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="file" minOccurs="0" maxOccurs="unbounded" type="tns:FileType"/>
            </xs:sequence>
			<xs:attribute name="filelist_version" type="xs:string" use="required"/>
            <xs:attribute name="account_id" type="xs:long"/>
			<xs:attribute name="app_id" type="xs:long"/>
			<xs:attribute name="sandbox_id" type="xs:long" use="optional"/>
			<xs:attribute name="build_id" type="xs:long"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="FileType">
        <xs:annotation>
            <xs:documentation>
                The file type element contains the key elements and attributes
                that reflect the data we store for a file.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="file_id" type="xs:long"/>
        <xs:attribute name="file_name" type="tns:LongRequiredTextType"/>
        <xs:attribute name="file_status" type="tns:StatusType"/>
        <xs:attribute name="file_md5" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="LongTextType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="1024"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="LongRequiredTextType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="1024"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DescTextType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="4000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="StatusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Pending Upload"/>
            <xs:enumeration value="Uploading"/>
            <xs:enumeration value="Purged"/> 
            <xs:enumeration value="Uploaded"/> 
            <xs:enumeration value="Missing"/>
            <xs:enumeration value="Partial"/>
            <xs:enumeration value="Invalid Checksum"/>
            <xs:enumeration value="Invalid Archive"/>
            <xs:enumeration value="Archive File Within Another Archive"/>
            <xs:enumeration value="Archive File with Unsupported Compression"/>
            <xs:enumeration value="Archive File is Password Protected"/>
       </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== dennismedeiros/veracode-platform-api-framework/platform-api-parsers/src/test/resources/xml/filelist.xml
<filelist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://analysiscenter.veracode.com/schema/2.0/filelist" xsi:schemaLocation="https://analysiscenter.veracode.com/schema/2.0/filelist https://analysiscenter.veracode.com/resource/2.0/filelist.xsd" filelist_version="1.1" account_id="1" app_id="151633" sandbox_id="1498045" build_id="5219199">
<file file_id="6484501810" file_name="ExportBankCustAcctDll.pdb" file_status="Uploaded" file_md5="53840fdcfbadaadd5dc58e518fc67301"/>
<file file_id="6484501821" file_name="ExportClassifDll.dll" file_status="Uploaded" file_md5="8bec68c63b234732ec82f783aa0f88b0"/>
<file file_id="6484501771" file_name="DATA_AGG.res.ja-JP.dll" file_status="Uploaded" file_md5="12ad33f8d0c56c75b932faf56ec11a56"/>
<file file_id="6484501775" file_name="DBGTRACE.dll" file_status="Uploaded" file_md5="544b06045c7ca7fe1bf5d16cfdb83b33"/>
<file file_id="6484501777" file_name="DelCashAcct.pdb" file_status="Uploaded" file_md5="8469dff1f5101010b4871ae0d6d440b2"/>
<file file_id="6484501786" file_name="Dyncomp.res.ja-JP.dll" file_status="Uploaded" file_md5="1ce7260de834b49dcb56134a78b1fa4d"/>
<file file_id="6484501804" file_name="exportanaldll.pdb" file_status="Uploaded" file_md5="ba1db0d0bc892c9c94c60600b6710755"/>
<file file_id="6484783197" file_name="amqzc.dll" file_status="Uploaded" file_md5="1493f566a2522fffb848c4166596e137"/>
<file file_id="6484783201" file_name="amqzsai.dll" file_status="Uploaded" file_md5="5cf11e38de7561a064a8761ea1221bbe"/>
<file file_id="6484501807" file_name="ExportBankCashAcctDll.dll" file_status="Uploaded" file_md5="e9f60aa5235c7ae3f373d487d650e082"/>
<file file_id="6484501812" file_name="ExportBaseRatedll.pdb" file_status="Uploaded" file_md5="69eddc59f2cee6b4b42f5276ce8b8831"/>
<file file_id="6484501816" file_name="ExportBrokerDll.pdb" file_status="Uploaded" file_md5="a76c5830adabcca1169a31a6d83e0871"/>
<file file_id="6484501824" file_name="ExportCollPosDll.pdb" file_status="Uploaded" file_md5="47917dcc003ed04cd2f145cb1d9dcae5"/>
<file file_id="6484501826" file_name="ExportContactsDll.pdb" file_status="Uploaded" file_md5="576dd677b4b3a71a04fed4121cc09da6"/>
<file file_id="6484501830" file_name="exportcountrydll.pdb" file_status="Uploaded" file_md5="d370bc1e900afd5426dc6e3359d2e9f3"/>
<file file_id="6484505035" file_name="ExportDivAccrualDll.dll" file_status="Uploaded" file_md5="d698b992fe9f4e0182cf13623feabf00"/>
<file file_id="6484910840" file_name="IMPORT.res.ja-JP.dll" file_status="Uploaded" file_md5="d696e4df9a3a08d996ac8ec4ef441412"/>
<file file_id="6484910841" file_name="importobj.pdb" file_status="Uploaded" file_md5="fdcf047c2a80ceba5b8ccc46add6d257"/>
<file file_id="6484501772" file_name="dbgtrace.pdb" file_status="Uploaded" file_md5="c972e88b1b984476b208b0ffbcda19b4"/>
<file file_id="6484910855" file_name="INCSVR.dll" file_status="Uploaded" file_md5="33818c6fcc82dd588446f540a7358979"/>
<file file_id="6484501819" file_name="ExportCashForecastDll.dll" file_status="Uploaded" file_md5="ca6e07b9fe2aaeb3c2e2ebeedcf393a7"/>
<file file_id="6484501832" file_name="exportcurrencydll.pdb" file_status="Uploaded" file_md5="08cd9b09e3097b9bb468c7b9336460cc"/>
<file file_id="6484505047" file_name="ExportIntRateDll.dll" file_status="Uploaded" file_md5="4ee7f1b46475fef5b00e2b839c74f229"/>
<file file_id="6484505048" file_name="ExportIntRateDll.pdb" file_status="Uploaded" file_md5="d2c102ea00c983833c70d9ae84a93b3d"/>
<file file_id="6484501794" file_name="ENGINE.res.ja-JP.dll" file_status="Uploaded" file_md5="2de4eb04124722e3e1d9209cd542b32c"/>
<file file_id="6484501795" file_name="eurosvr.res.ja_jp.pdb" file_status="Uploaded" file_md5="30fd82fad55d14aab0b598947bda8937"/>
<file file_id="6484501798" file_name="EUROSVR.dll" file_status="Uploaded" file_md5="6e8664a5b5ec3a7f395bbabb920e683d"/>
<file file_id="6484501800" file_name="EUROSVR.pdb" file_status="Uploaded" file_md5="85294fd3ee41ffa1e420bcab839a3a6a"/>
<file file_id="6484505045" file_name="ExportGeneralLedgerDll.dll" file_status="Uploaded" file_md5="59a219b33326af90c6a8941364a42094"/>
<file file_id="6484505052" file_name="ExportIssuerDll.pdb" file_status="Uploaded" file_md5="8373be10636bdd342d6795261baf547b"/>
<file file_id="6484501813" file_name="ExportBaseRateDll.dll" file_status="Uploaded" file_md5="f895d06817ce51c636baeb50c151c0f4"/>
<file file_id="6484505037" file_name="ExportDivAccrualDll.pdb" file_status="Uploaded" file_md5="a8273f61421e5de7e47a589fe8c57da5"/>
<file file_id="6484505053" file_name="ExportLocHoldingDll.dll" file_status="Uploaded" file_md5="d0261fe115dfd3243e26a715ad2f406c"/>
<file file_id="6484505054" file_name="ExportLocHoldingDll.pdb" file_status="Uploaded" file_md5="ab129cd575fe0435449d498fd099b587"/>
<file file_id="6484505041" file_name="ExportEntityDll.pdb" file_status="Uploaded" file_md5="a193d816cf01d872efa32b22892388d5"/>
<file file_id="6484505042" file_name="ExportFxRateDll.dll" file_status="Uploaded" file_md5="dc6a217c5fc36a9ab79471cf8c1498c7"/>
<file file_id="6484792846" file_name="PFSFRAME.res.ja-JP.dll" file_status="Uploaded" file_md5="337118cc944841f7b5d2b96bb8c08481"/>
<file file_id="6484916767" file_name="portsel.pdb" file_status="Uploaded" file_md5="cabe8921522b0ff655d66e9c90325fc3"/>
<file file_id="6484916769" file_name="portsvr.dll" file_status="Uploaded" file_md5="56ca6df9875bf843ebe9291c9a46115f"/>
<file file_id="6484505087" file_name="ExportSwapDealsDll.dll" file_status="Uploaded" file_md5="b8c3ab1704480bef26e02547707a9ea0"/>
<file file_id="6484505094" file_name="ExportTranUdfDll.dll" file_status="Uploaded" file_md5="b3eee56af9fc4004c026f063ba6d9ce5"/>
<file file_id="6484505119" file_name="FUTSVR.dll" file_status="Uploaded" file_md5="e36d76b309814347e856674536e3a782"/>
<file file_id="6484505121" file_name="global.res.ja_jp.pdb" file_status="Uploaded" file_md5="68bdb5f51211ccad9d9b2d04ac4d2cf2"/>
<file file_id="6484505132" file_name="glsvr.res.ja_jp.pdb" file_status="Uploaded" file_md5="66f30324d0aa2bd0613cd6793db1590a"/>
<file file_id="6484910837" file_name="ImpObj.dll" file_status="Uploaded" file_md5="e06fd71bb487357e71ebabd2c96df649"/>
<file file_id="6484787076" file_name="LOCBAL.exe" file_status="Uploaded" file_md5="afee95400565d5e2b42a856a5b6754db"/>
<file file_id="6484787078" file_name="locdlgs.pdb" file_status="Uploaded" file_md5="9dcd25416d6526b2628f7ce98ff14ad5"/>
<file file_id="6484787088" file_name="LOCDLGS.res.ja-JP.dll" file_status="Uploaded" file_md5="f1dc97183c36c0fcb7352c6297d00262"/>
<file file_id="6484787090" file_name="lp305a.pdb" file_status="Uploaded" file_md5="3306b1cbb9d11adfa73f578c1465b21b"/>
<file file_id="6484787124" file_name="LP902E.exe" file_status="Uploaded" file_md5="b7c93dce53e3319d53f485aba57c3e2f"/>
<file file_id="6484787127" file_name="lpanstat.pdb" file_status="Uploaded" file_md5="cdbd001904f9272d1071a1471a18f49b"/>
<file file_id="6484787131" file_name="lstapsum.pdb" file_status="Uploaded" file_md5="b599bbcfa16879821bc24ebc1f569770"/>
<file file_id="6484787120" file_name="LP317G.exe" file_status="Uploaded" file_md5="673ffda7a681fac8ec2a2ba801bbe260"/>
<file file_id="6484505059" file_name="ExportMortFactDll.pdb" file_status="Uploaded" file_md5="e59b0c68c91364e6cd0a845b156a3c67"/>
<file file_id="6484505069" file_name="ExportPortDll.pdb" file_status="Uploaded" file_md5="d1d00373b38b8b67f53f24ad6e5654ae"/>
<file file_id="6484505071" file_name="ExportRatDll.pdb" file_status="Uploaded" file_md5="0383818226b17cd3a4d99d255f5dad22"/>
<file file_id="6484505081" file_name="ExportSMFDll.dll" file_status="Uploaded" file_md5="57a02cf86d3044157c0f3e7d16e61574"/>
<file file_id="6484505089" file_name="ExportTaxLotAdjDetDll.dll" file_status="Uploaded" file_md5="a05d72ca2e3af88e16d1cddcc140caf4"/>
<file file_id="6484505104" file_name="ExportWithholdTaxRateDll.pdb" file_status="Uploaded" file_md5="99f928fe58753390290db8d103f452e2"/>
<file file_id="6484505110" file_name="FFXSVR.dll" file_status="Uploaded" file_md5="6a123af57c46ad006830ce2790f889d5"/>
<file file_id="6484505114" file_name="formula.res.ja_jp.pdb" file_status="Uploaded" file_md5="49c2fe14e57f118678d14b2ced292542"/>
<file file_id="6484505116" file_name="Formula.res.ja-JP.dll" file_status="Uploaded" file_md5="1cc128099c4c1cbcb2a3941425ce92ba"/>
<file file_id="6484505117" file_name="futsvr.pdb" file_status="Uploaded" file_md5="11301becdc04d5f6882fc0f2c822247b"/>
<file file_id="6484505120" file_name="global.pdb" file_status="Uploaded" file_md5="a55ab0670992e72499fad30b33659e64"/>
<file file_id="6484505124" file_name="Global.dll" file_status="Uploaded" file_md5="88a1bb07f55d85a09eec51355476ca16"/>
<file file_id="6484910839" file_name="import.res.ja_jp.pdb" file_status="Uploaded" file_md5="dfdfc5ef3f530e781f2f85682093aefa"/>
<file file_id="6484910907" file_name="listfasb.pdb" file_status="Uploaded" file_md5="52a7d7bc79ea36677e2c009c665e3a03"/>
<file file_id="6484505079" file_name="ExportSecurityPriceDll.pdb" file_status="Uploaded" file_md5="630ec4e9d7e578f775ffc2462fce2db4"/>
<file file_id="6484505083" file_name="ExportSMFDll.pdb" file_status="Uploaded" file_md5="dbf60efd3b68840354ce83919d5d23a7"/>
<file file_id="6484505092" file_name="ExportTranDll.dll" file_status="Uploaded" file_md5="08d34c8c81c0c8016f2ee1da00d378f4"/>
<file file_id="6484505101" file_name="ExportValuationDll.dll" file_status="Uploaded" file_md5="7b18782eda720ca87ac46f8cd3bfaa9e"/>
<file file_id="6484505102" file_name="ExportValuationDll.pdb" file_status="Uploaded" file_md5="79dbf826d8caf201b6ac918de494ab7f"/>
<file file_id="6484505107" file_name="feedlg.res.ja_jp.pdb" file_status="Uploaded" file_md5="891d13f65d4b77ff50e7760d75c88312"/>
<file file_id="6484910843" file_name="importobj.res.ja_jp.pdb" file_status="Uploaded" file_md5="cc40bc57d29dd631c0e08e6a9d9ca1c7"/>
<file file_id="6484910857" file_name="IniUtil.res.ja-JP.dll" file_status="Uploaded" file_md5="52744f15f2769cb354111e5bd34794d6"/>
<file file_id="6484910915" file_name="listfeei.pdb" file_status="Uploaded" file_md5="62e5f02bd9133d980d734ae4f93874b3"/>
