=== dennismedeiros/veracode-platform-api-framework/platform-api-parsers/src/test/resources/xsd/mitigationinfo.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  Schema definition for the Mitigation Info XML.
  Veracode, Inc., 2012.
-->
<xs:schema elementFormDefault="qualified" version="1.1"
   targetNamespace="https://analysiscenter.veracode.com/schema/mitigationinfo/1.0"
   xmlns:tns="https://analysiscenter.veracode.com/schema/mitigationinfo/1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="mitigationinfo">
        <xs:annotation>
            <xs:documentation>
                This is a wrapper for the entire Mitigation Info xml file.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="issue" minOccurs="0" maxOccurs="unbounded" type="tns:IssueType"/>
                <xs:element name="error" minOccurs="0" maxOccurs="unbounded" type="tns:ErrorType"/>
            </xs:sequence>
            <xs:attribute name="mitigationinfo_version" type="xs:string" use="optional"/>
            <xs:attribute name="build_id" type="xs:long"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="IssueType">
        <xs:annotation>
            <xs:documentation>
                The issue type element contains the attributes and mitigation action
                elements stored for a flaw.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
          <xs:element name="mitigation_action" minOccurs="0" maxOccurs="unbounded" type="tns:MitigationActionType"/>
        </xs:sequence>
        <xs:attribute name="flaw_id" type="xs:long"/>
        <xs:attribute name="category" type="tns:LongRequiredTextType"/>
    </xs:complexType>

    <xs:complexType name="ErrorType">
        <xs:annotation>
            <xs:documentation>
                The error type element contains the list of ids which could not be processed.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="flaw_id_list" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="MitigationActionType">
        <xs:attribute name="action" type="tns:ActionTypeType"/>
        <xs:attribute name="desc" type="xs:string"/>
        <xs:attribute name="reviewer" type="xs:string"/>
        <xs:attribute name="date" type="xs:string"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="LongRequiredTextType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="1024"/>
        </xs:restriction>
    </xs:simpleType>

   <xs:simpleType name="ActionTypeType">
       <xs:restriction base="xs:string">
         <xs:enumeration value="comment"/>
         <xs:enumeration value="fp"/>
         <xs:enumeration value="appdesign"/>
         <xs:enumeration value="osenv"/>
         <xs:enumeration value="netenv"/>
         <xs:enumeration value="rejected"/>
         <xs:enumeration value="accepted"/>
         <xs:enumeration value="remediated"/>
         <xs:enumeration value="noactiontaken"/>
         <xs:enumeration value="conforms"/>
         <xs:enumeration value="deviates"/>
       </xs:restriction>
   </xs:simpleType>

</xs:schema>

=== dennismedeiros/veracode-platform-api-framework/platform-api-parsers/src/test/resources/xml/mitigationinfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<mitigationinfo xmlns="https://analysiscenter.veracode.com/schema/mitigationinfo/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" build_id="2726817" mitigationinfo_version="1.1" xsi:schemaLocation="https://analysiscenter.veracode.com/schema/mitigationinfo/1.0 https://analysiscenter.veracode.com/resource/mitigationinfo.xsd">
  <issue category="Improper Output Neutralization for Logs" flaw_id="3">
      <mitigation_action action="appdesign" comment="&#13;Technique : M2 :  Establish and maintain control over all of your outputs&#13;&#10;Specifics : This is a prpposal&#13;&#10;Remaining Risk : asdf&#13;&#10;Verification : asdf" date="2018-08-21 11:49:40" desc="Mitigate by Design" reviewer="Dennis Medeiros"/>
      <mitigation_action action="comment" comment="&lt;script&gt;alert('325')&lt;/script&gt;" date="2018-08-30 12:32:44" desc="Add Comment" reviewer="Dennis Medeiros"/>
      <mitigation_action action="comment" comment="&lt;script&gt;alert();&lt;/script&gt;" date="2018-08-30 12:36:44" desc="Add Comment" reviewer="Dennis Medeiros"/>
      <mitigation_action action="comment" comment="&lt;td align=&quot;left&quot; valign=&quot;middle&quot;&gt;Rejected&lt;/td&gt;/*" date="2018-08-30 12:38:59" desc="Add Comment" reviewer="Dennis Medeiros"/>
      <mitigation_action action="comment" comment="&lt;td align=&quot;left&quot; valign=&quot;middle&quot;&gt;Rejected&lt;/td&gt;&lt;--" date="2018-08-30 12:46:04" desc="Add Comment" reviewer="Dennis Medeiros"/>
      <mitigation_action action="deviates" comment="asdfasdfasdf" date="2018-09-20 12:18:19" desc="Deviates from Guidelines" reviewer="Veracode"/>
      <mitigation_action action="comment" comment="Test" date="2018-09-20 12:19:43" desc="Add Comment" reviewer="Dennis Medeiros"/>
      <mitigation_action action="conforms" comment="asdfasdfas" date="2018-09-20 12:20:01" desc="Conforms to Guidelines" reviewer="Veracode"/>
      <mitigation_action action="comment" comment="Test" date="2018-09-20 12:20:53" desc="Add Comment" reviewer="Dennis Medeiros"/>
   </issue>
</mitigationinfo>
